### ISSUE TITLE
JE-00008 Build is failing due to outdated library version

### ISSUE THREAD

**Issue by jesperancinha** [jesperancinha/image-train-filters-scala#19]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.artima.supersafe:sbtplugin:1.1.0-RC6 (scalaVersion=2.10, sbtVersion=0.13) (/home/circleci/repo/project/plugins.sbt#L10-11)
[warn] 		  +- default:repo-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.artima.supersafe#sbtplugin;1.1.0-RC6: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)

**Comment by jesperancinha** [comment]
Major update was needed and some libraries had to thrown away altogether.
